# Generated by Django 5.2.17 on 2026-09-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_developer',
            field=models.BooleanField(default=False, help_text='Sees every staff page plus the /dev/ database tools. Not granted to ordinary logins.'),
        ),
    ]
