# Generated by Django 5.2.17 on 2026-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0002_alter_transfer_options_transferline'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblproduct_transfer.nid — lets a re-sync from iadmin update this exact transfer instead of duplicating it.', null=True, unique=True),
        ),
    ]
