# Generated by Django 5.2.17 on 2026-08-19 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("locations", "0001_initial"),
        ("transfers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scan_index",
                    models.PositiveIntegerField(editable=False, unique=True),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("OPENING", "Opening count"),
                            ("CLOSING", "Closing count"),
                            ("CHECK", "Check item"),
                        ],
                        max_length=10,
                    ),
                ),
                ("item_count", models.PositiveIntegerField(default=0)),
                ("is_transfer", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracker_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracker_sessions",
                        to="locations.location",
                    ),
                ),
                (
                    "parent_session",
                    models.ForeignKey(
                        blank=True,
                        help_text="For a CLOSING session, the OPENING session(s) it closes out.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closing_sessions",
                        to="tracker.trackersession",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracker_sessions",
                        to="transfers.transfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-scan_index"],
            },
        ),
        migrations.CreateModel(
            name="TrackerScanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPANY_STOCK", "Company stock"),
                            ("ASSIGNED", "Assigned"),
                            ("SOLD", "Sold"),
                            ("RESERVED", "Reserved"),
                            ("LOSS", "Loss"),
                            ("ELSEWHERE", "Elsewhere"),
                            ("WRONG_LOCATION", "Wrong location"),
                            ("NOT_FOUND", "Not found"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tracker_scans",
                        to="inventory.productitem",
                    ),
                ),
                (
                    "location_at_scan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="locations.location",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_items",
                        to="tracker.trackersession",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "item__barcode"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "item"), name="unique_item_per_session"
                    )
                ],
            },
        ),
    ]
