# Generated by Django 5.2.17 on 2026-08-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerscanitem',
            name='is_extra',
            field=models.BooleanField(default=False, help_text="Scanned in a closing/check session but wasn't part of the opening baseline set."),
        ),
        migrations.AlterField(
            model_name='trackerscanitem',
            name='result',
            field=models.CharField(blank=True, choices=[('COMPANY_STOCK', 'Company stock'), ('ASSIGNED', 'Assigned'), ('SOLD', 'Sold'), ('RESERVED', 'Reserved'), ('LOSS', 'Loss'), ('ELSEWHERE', 'Elsewhere'), ('WRONG_LOCATION', 'Wrong location'), ('NOT_FOUND', 'Not found'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
