# Generated by Django 5.2.17 on 2026-09-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_trackerscanitem_is_extra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackersession',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblproduct_tracker.nid — lets a re-sync from iadmin update this exact session instead of duplicating it.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='trackersession',
            name='mode',
            field=models.CharField(choices=[('OPENING', 'Opening count'), ('CLOSING', 'Closing count'), ('CHECK', 'Check item'), ('FIND', 'Find item'), ('TRANSFER', 'Transfer scan')], max_length=10),
        ),
    ]
