# Generated by Django 5.2.17 on 2026-09-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnrecord',
            options={'ordering': ['-created_at'], 'permissions': [('can_process_return', 'Can process returns / reserve / confirm-sold')]},
        ),
    ]
