# Generated by Django 5.2.17 on 2026-08-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_label', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('kind', models.CharField(choices=[('INVOICE_PDF', 'Generated invoice PDF'), ('PAYMENT_PROOF', 'Proof of payment'), ('LOCATION_LOGO', 'Reseller-location logo'), ('OTHER', 'Other legacy file')], db_index=True, default='OTHER', max_length=20)),
                ('file', models.FileField(upload_to='legacy/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('source_path', models.CharField(blank=True, help_text='Where this came from in the legacy tree, for audit.', max_length=500)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_label', 'object_id', 'kind'], name='core_legacy_model_l_0c95d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('model_label', 'object_id', 'sha256'), name='unique_legacy_document_per_object')],
            },
        ),
    ]
