# Generated by Django 5.2.17 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resellerpayment',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblAssignPayment_transaction.nid — lets a re-sync from iadmin update this exact payment instead of duplicating it.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblpayment_transaction.nid — lets a re-sync from iadmin update this exact payment instead of duplicating it.', null=True, unique=True),
        ),
    ]
