# Generated by Django 5.2.17 on 2026-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("HEAD_OFFICE", "Head Office"),
                            ("BRANCH", "Branch"),
                            ("SHOWROOM", "Showroom"),
                            ("WAREHOUSE", "Warehouse"),
                            ("PULLOUT", "Pullout"),
                            ("OTHER", "Other"),
                        ],
                        default="BRANCH",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
