# Generated by Django 5.2.17 on 2026-09-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
    ]
