# Generated by Django 5.2.17 on 2026-08-19 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "barcode",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "rfid_epc",
                    models.CharField(
                        blank=True,
                        help_text="RFID chip payload. Legacy ZPL templates wrote the barcode string itself here (^RFW,a,2,,A ^FD{barcode}) — kept as the default unless a distinct EPC scheme is adopted.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Company stock (pending)"),
                            ("ASSIGNED", "Assigned to reseller"),
                            ("RESERVED", "Reserved"),
                            ("SOLD", "Sold"),
                            ("IN_TRANSIT", "In transit (transfer in progress)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reprint_status",
                    models.CharField(
                        choices=[
                            ("NONE", "Not printed"),
                            ("PRINTED", "Printed"),
                            ("REPRINT_PENDING", "Reprint pending approval"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="locations.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="catalogue.productmaster",
                    ),
                ),
            ],
            options={
                "ordering": ["barcode"],
                "indexes": [
                    models.Index(
                        fields=["status", "location"],
                        name="inventory_p_status_2fda79_idx",
                    )
                ],
            },
        ),
    ]
