# Generated by Django 5.2.17 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblproduct_detail_master.nid — lets a re-sync from iadmin update this exact item instead of duplicating it.', null=True, unique=True),
        ),
    ]
