# Generated by Django 5.2.17 on 2026-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                help_text="JW / ST / FI / MT — drives ZPL label template routing (legacy tbljewellery_type).",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="productmaster",
            name="subcategory",
            field=models.CharField(
                blank=True,
                help_text="Legacy tblsub_category_master name (Ring, Necklace, …). Category itself is the jewellery type (JW/ST/FI/MT) used for ZPL routing.",
                max_length=100,
            ),
        ),
    ]
