# Generated by Django 5.2.17 on 2026-08-27 13:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_category_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='convert_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='tblproduct_master.Converte_rate. Multiplies price on the printed invoice.', max_digits=12),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='metal_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='tblproduct_master.metalrate — per-gram price, shown on gold invoice lines.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='rate_change_status',
            field=models.CharField(blank=True, help_text="'apply' means use update_convert_rate; anything else means use convert_rate.", max_length=20),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='update_convert_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Pending replacement rate; used instead of convert_rate when rate_change_status is 'apply'.", max_digits=12, null=True),
        ),
    ]
