# Generated by Django 5.2.17 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_productmaster_convert_rate_productmaster_metal_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblproduct_master.nid — lets a re-sync from iadmin update this exact design instead of duplicating it.', null=True, unique=True),
        ),
    ]
