# Generated by Django 5.2.17 on 2026-08-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_productmaster_legacy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='product_images/%Y/%m/')),
                ('kind', models.CharField(choices=[('PHOTO', 'Product photo'), ('CERT', 'Certificate'), ('OTHER', 'Other')], default='PHOTO', max_length=8)),
                ('is_primary', models.BooleanField(default=False, help_text='Shown first wherever a single thumbnail is needed.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('source_filename', models.CharField(blank=True, db_index=True, help_text='Original file this came from — a re-import skips a (product, source_filename) pair already stored.', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalogue.productmaster')),
            ],
            options={
                'ordering': ['-is_primary', 'order', 'id'],
                'indexes': [models.Index(fields=['product', 'is_primary'], name='catalogue_p_product_498ad7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image_per_product')],
            },
        ),
    ]
