# Generated by Django 5.2.17 on 2026-09-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_productmaster_consignment_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='False for a design created from an unverified source (e.g. photographed into almarphoto) with no matching iadmin/RFID record yet — legacy_id is null and nothing here has been confirmed against actual tagged stock. A later legacy sync that finds a matching barcode/reference_id should flip this back to True and reuse this row rather than creating a duplicate.'),
        ),
    ]
