# Generated by Django 5.2.17 on 2026-09-11 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_productmaster_is_verified'),
        ('inventory', '0002_productitem_legacy_id'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductIntakeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_no', models.PositiveIntegerField(db_index=True)),
                ('source', models.CharField(choices=[('excel', 'Jewellery Excel'), ('form', 'One piece')], default='excel', max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('workbook', models.FileField(blank=True, upload_to='intake_uploads/%Y/%m/')),
                ('sheet', models.CharField(blank=True, max_length=100)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Caught'), ('partial', 'Caught with row errors'), ('failed', 'Not this file')], default='success', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_intake_batches', to='locations.location')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_intake_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductIntakeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(choices=[('created', 'New'), ('updated', 'Updated'), ('error', 'Skipped')], max_length=10)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='catalogue.productintakebatch')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_lines', to='inventory.productitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
