# Generated by Django 5.2.17 on 2026-09-14 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_alter_productimage_thumbnail_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('single', 'Attach to PJ'), ('bulk', 'Bulk by filename'), ('stage', 'Stage / floating'), ('assign', 'Manual assign'), ('claim', 'Auto-claim on stock'), ('cli', 'Management command'), ('api', 'API')], default='single', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, help_text='Where the upload came from, e.g. photo_upload UI / API / import_product_images.', max_length=80)),
                ('target_code', models.CharField(blank=True, help_text='PJ / barcode typed for a single-design attach, if any.', max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('files_total', models.PositiveIntegerField(default=0)),
                ('attached_count', models.PositiveIntegerField(default=0)),
                ('staged_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_upload_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StagedProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='product_images/staged/%Y/%m/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='product_images/staged/thumbs/%Y/%m/')),
                ('source_filename', models.CharField(db_index=True, max_length=255)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('PHOTO', 'Product photo'), ('CERT', 'Certificate'), ('OTHER', 'Other')], default='PHOTO', max_length=8)),
                ('extracted_codes', models.JSONField(blank=True, default=list, help_text='PJ tokens parsed from the filename at upload time.')),
                ('hinted_code', models.CharField(blank=True, db_index=True, help_text='Primary code to match — first extracted token, or a code typed by the uploader.', max_length=40)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for PJ'), ('attached', 'Attached to design'), ('skipped', 'Skipped (duplicate)'), ('failed', 'Failed'), ('discarded', 'Discarded')], db_index=True, default='waiting', max_length=12)),
                ('status_detail', models.CharField(blank=True, max_length=500)),
                ('attached_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('attached_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_attachments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogue.photouploadbatch')),
                ('discarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_discards', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_photos', to='catalogue.productmaster')),
                ('product_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_source', to='catalogue.productimage')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'hinted_code'], name='catalogue_s_status_70d1bc_idx'), models.Index(fields=['status', 'created_at'], name='catalogue_s_status_6da25d_idx')],
            },
        ),
    ]
