# Generated by Django 5.2.17 on 2026-08-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(help_text='Short code used on screens and reports, e.g. GRP-A.', max_length=20, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reseller',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Nullable on purpose — every existing reseller row stays valid and simply shows as ungrouped until someone files it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='assignment.resellergroup'),
        ),
    ]
