# Generated by Django 5.2.17 on 2026-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0002_resellergroup_reseller_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentmaster",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stored so imported legacy numbers (RE00128, RN00004, …) survive. New rows get a fixed-width RE/RN + id if left blank.",
                max_length=32,
            ),
        ),
    ]
