# Generated by hand (no local Django install in this shell), matching the
# style of 0003_assignmentmaster_invoice_number.py, for Django 5.2.17.
# Adds the commission fields ported from pj-accounting's invoice model
# (see AssignmentLine's docstring in models.py).

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignment", "0003_assignmentmaster_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentline",
            name="commission_type",
            field=models.CharField(
                blank=True,
                choices=[("GOLD", "Gold (rate per gram)"), ("JEWELRY", "Jewelry (rate x line total)")],
                help_text="Leave blank if this line carries no reseller commission.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="assignmentline",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Pesos per gram for GOLD, or a fraction (e.g. 0.05) of the line total for JEWELRY.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignmentline",
            name="commission_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Auto-computed from commission_rate/commission_type on save unless commission_overridden is set.",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="assignmentline",
            name="commission_overridden",
            field=models.BooleanField(
                default=False,
                help_text="True once a human has set commission_value directly — mirrors pj-accounting's commissionValue-supplied-by-admin override rule. Auto-calculation stops touching it after that; use set_commission_override() to flip it deliberately rather than editing the field directly.",
            ),
        ),
    ]
