# Generated by Django 5.2.17 on 2026-08-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_assignmentline_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResellerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('logo', models.FileField(blank=True, upload_to='reseller_logos/')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, help_text='tblresellerlocationMaster.nid — how imported invoices find their banner.', null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='reseller',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='reseller',
            name='contact',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='reseller',
            name='email',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reseller',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblResellerMaster.nid. Printed on invoices as "Res No.".', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='assignmentmaster',
            name='reseller_location',
            field=models.ForeignKey(blank=True, help_text='Which reseller branch this was issued under — drives the invoice banner and logo. Legacy tblProductAssignMaster.reseller_locationid.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignment.resellerlocation'),
        ),
    ]
