# Generated by Django 5.2.17 on 2026-08-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_resellerlocation_reseller_address_reseller_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentmaster',
            name='legacy_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='tblProductAssignMaster.nid — lets a re-sync from iadmin update this exact invoice instead of duplicating it.', null=True, unique=True),
        ),
    ]
