# Generated by Django 5.2.17 on 2026-09-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_assignmentmaster_legacy_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentmaster',
            options={'ordering': ['-created_at'], 'permissions': [('can_create_invoice', 'Can assign stock to a reseller (create invoice)'), ('can_stamp_invoice', 'Can stamp / finalize an invoice'), ('can_add_charge', 'Can add charges / credits on an invoice')]},
        ),
    ]
