# Generated by Django 5.2.17 on 2026-08-25 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('JW', 'Jewellery'), ('ST', 'Stone'), ('FI', 'Finding'), ('MT', 'Metal'), ('ANY', 'Any category (fallback)')], default='ANY', max_length=5)),
                ('is_default', models.BooleanField(default=False, help_text='Used automatically when printing an item in this category without picking a template explicitly. Only one default per category.')),
                ('width_dots', models.PositiveIntegerField(default=785, help_text='Label width in printer dots — matches the ZPL ^PW command.')),
                ('height_dots', models.PositiveIntegerField(default=400, help_text="Label height in printer dots. Design-canvas only; ZPL itself doesn't need a ^LL for continuous/RFID stock.")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='label_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_key', models.CharField(choices=[('barcode_number', 'Barcode number (text)'), ('barcode_image', 'Barcode (scannable)'), ('reference_id', 'Reference / SKU'), ('product_name', 'Product name'), ('metal', 'Metal'), ('metal_purity', 'Metal purity'), ('stone', 'Stone'), ('colour', 'Colour'), ('quality', 'Quality'), ('weight', 'Net weight'), ('price', 'Price'), ('currency', 'Currency'), ('size', 'Size'), ('company_name', 'Company name'), ('static_text', 'Custom text')], max_length=20)),
                ('static_text', models.CharField(blank=True, help_text="Full text when field_key = Custom text; otherwise an optional label/prefix in front of the field's value.", max_length=200)),
                ('x', models.PositiveIntegerField(default=10)),
                ('y', models.PositiveIntegerField(default=10)),
                ('font_size', models.PositiveIntegerField(default=24)),
                ('bold', models.BooleanField(default=False)),
                ('align', models.CharField(choices=[('L', 'Left'), ('C', 'Center'), ('R', 'Right')], default='L', max_length=1)),
                ('box_width', models.PositiveIntegerField(default=300, help_text='Text box width in dots — drives ZPL ^FB wrapping/alignment.')),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='hardware.labeltemplate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
