# Generated by Django 5.2.17 on 2026-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='dpi',
            field=models.PositiveIntegerField(default=203, help_text='Printer DPI used to convert mm↔dots for the paper outline (Zebra desktop default is 203).'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='media_profile',
            field=models.CharField(choices=[('irys_standard', 'Irys Standard RFID (25×13 + 50mm tail)'), ('blank', 'Blank rectangle')], default='irys_standard', help_text='Paper die-cut overlay in the designer (Irys jewellery RFID vs free rectangle).', max_length=40),
        ),
        migrations.AlterField(
            model_name='labelfield',
            name='box_width',
            field=models.PositiveIntegerField(default=180, help_text='Text box width in dots — drives ZPL ^FB wrapping/alignment.'),
        ),
        migrations.AlterField(
            model_name='labelfield',
            name='field_key',
            field=models.CharField(choices=[('barcode_number', 'PJ number (barcode text)'), ('barcode_image', 'Barcode (scannable)'), ('reference_id', 'Item code / SKU'), ('product_name', 'Product name'), ('supplier_code', 'Supplier code'), ('supplier_name', 'Supplier name'), ('subcategory', 'Subcategory'), ('category_code', 'Category code (JW/ST/…)'), ('metal', 'Metal'), ('metal_purity', 'Metal purity'), ('stone', 'Stone'), ('colour', 'Colour'), ('quality', 'Quality'), ('weight', 'Net weight'), ('gross_weight', 'Gross weight'), ('size', 'Size'), ('price', 'Selling price'), ('price_rated', 'Selling price × rate'), ('currency', 'Currency'), ('company_name', 'Company name'), ('static_text', 'Custom text'), ('horizontal_line', 'Divider line')], max_length=20),
        ),
        migrations.AlterField(
            model_name='labelfield',
            name='font_size',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='height_dots',
            field=models.PositiveIntegerField(default=208, help_text='Label height in printer dots — emitted as ^LL. Irys Standard @ 203 DPI ≈ 208 (26 mm flat).'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='width_dots',
            field=models.PositiveIntegerField(default=600, help_text='Label width in printer dots — matches the ZPL ^PW command. Irys Standard @ 203 DPI ≈ 600 (75 mm).'),
        ),
    ]
