# Generated by Django 5.2.17 on 2026-09-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0002_label_media_profile_and_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='category',
            field=models.CharField(choices=[('JWL', 'Jewellery'), ('SN', 'Stone'), ('FN', 'Finding'), ('MT', 'Metal'), ('GB', 'Gold Bricks'), ('SPP', 'Semi Precious'), ('UNK', 'Uncategorised'), ('ANY', 'Any category (fallback)')], default='ANY', max_length=5),
        ),
    ]
