# Generated by Django 5.2.17 on 2026-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_template_category_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplate',
            name='offset_x',
            field=models.IntegerField(default=0, help_text='Print X nudge in dots (positive shifts right). Use to align with the physical die-cut.'),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='offset_y',
            field=models.IntegerField(default=0, help_text='Print Y nudge in dots (positive shifts down). Use to align with the physical die-cut.'),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='height_dots',
            field=models.PositiveIntegerField(default=208, help_text='Label height in printer dots (designer canvas). Continuous RFID stock does not emit ^LL.'),
        ),
    ]
