# Generated by Django 5.x — LabelPrintLog for tag print history.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0009_irys_offset_x_stone"),
        ("inventory", "0002_productitem_legacy_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelPrintLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_id", models.UUIDField(db_index=True)),
                ("barcode", models.CharField(db_index=True, max_length=100)),
                ("template_name", models.CharField(blank=True, max_length=100)),
                ("printer_name", models.CharField(blank=True, max_length=200)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Sent to printer"), ("error", "Send failed")],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=300)),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="label_print_logs",
                        to="inventory.productitem",
                    ),
                ),
                (
                    "printed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="label_print_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_logs",
                        to="hardware.labeltemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="labelprintlog",
            index=models.Index(fields=["barcode", "-created_at"], name="hardware_la_barcode_fd15e7_idx"),
        ),
        migrations.AddIndex(
            model_name="labelprintlog",
            index=models.Index(fields=["status", "-created_at"], name="hardware_la_status_b1ce89_idx"),
        ),
    ]
