# Generated by Django 5.2.17 on 2026-09-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_ensure_jefffffff_layout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labeltemplate',
            options={'ordering': ['category', 'name'], 'permissions': [('can_manage_labels', 'Can design label templates'), ('can_print_label', 'Can print tags'), ('can_reprint_label', 'Can re-print tags')]},
        ),
    ]
